load("//starlark:gitops.bzl", "environment")

environment(
    name = "dev",
)

environment(
    name = "beta",
)

environment(
    name = "user",
)

environment(
    name = "preview",
)

environment(
    name = "prod",
)
