workspace(name = "example")

local_repository(
    name = "rules_k8s_cd",
    path = "..",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Rules go
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "b2038e2de2cace18f032249cb4bb0048abf583a36369fa98f687af1b3f880b26",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.48.1/rules_go-v0.48.1.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.48.1/rules_go-v0.48.1.zip",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.20.4")

# Protocol Buffers
http_archive(
    name = "com_google_protobuf",
    sha256 = "ab5c722861bdaacc934f5ef5e547f4a946df07dc67f02ef926ee6d9f9fb70df0",
    strip_prefix = "protobuf-27.2",
    urls = [
        "https://github.com/protocolbuffers/protobuf/archive/refs/tags/v27.2.zip",
    ],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

load("@rules_oci//oci:repositories.bzl", "LATEST_CRANE_VERSION", "oci_register_toolchains")

oci_register_toolchains(
    name = "oci",
    crane_version = LATEST_CRANE_VERSION,
)

load("@rules_oci//oci:pull.bzl", "oci_pull")

oci_pull(
    name = "nginx",
    digest = "sha256:db5e49f40979ce521f05f0bc9f513d0abacce47904e229f3a95c2e6d9b47f244",
    image = "docker.io/library/nginx",
)

load("@rules_k8s_cd//starlark:kubeconfig.bzl", "kubeconfig")

kubeconfig(
    name = "k8s_test",
    cluster = "loopkube",
    use_host_config = True,
)

load("@rules_k8s_cd//starlark:grype.bzl", "grype_setup")

grype_setup()

load("@rules_k8s_cd//starlark:kubeconfig.bzl", "kubeconfig")

kubeconfig(
    name = "loopkube",
    cluster = "loopkube",
    use_host_config = True,
)

load("@rules_k8s_cd//starlark:kubectl.bzl", "kubectl_setup")

kubectl_setup()
