#!/bin/bash
STABLE_GIT_COMMIT=$(git rev-parse --short HEAD)
STABLE_GIT_TAGS=$(git tag)
STABLE_GIT_PR=$GITHUB_PULLREQUEST

echo "STABLE_GIT_COMMIT $STABLE_GIT_COMMIT"
echo "STABLE_GIT_TAGS $STABLE_GIT_TAGS"
echo "STABLE_GIT_PR $STABLE_GIT_PR"

