load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "grype_toolchain",
    srcs = ["grype_toolchain.bzl"],
    visibility = ["//lib:__subpackages__"],
    deps = [
    ],
)

bzl_library(
    name = "dive_toolchain",
    srcs = ["dive_toolchain.bzl"],
    visibility = ["//lib:__subpackages__"],
    deps = [
    ],
)

bzl_library(
    name = "kubectl_toolchain",
    srcs = ["kubectl_toolchain.bzl"],
    visibility = ["//lib:__subpackages__"],
    deps = [
    ],
)