load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "grype_toolchain",
    srcs = ["grype_toolchain.bzl"],
    visibility = ["//lib:__subpackages__"],
    deps = [
    ],
)

bzl_library(
    name = "dive_toolchain",
    srcs = ["dive_toolchain.bzl"],
    visibility = ["//lib:__subpackages__"],
    deps = [
    ],
)

bzl_library(
    name = "kubectl_toolchain",
    srcs = ["kubectl_toolchain.bzl"],
    visibility = ["//lib:__subpackages__"],
    deps = [
    ],
)

bzl_library(
    name = "kyverno_toolchain",
    srcs = ["kyverno_toolchain.bzl"],
    visibility = ["//lib:__subpackages__"],
    deps = [
    ],
)

bzl_library(
    name = "trivy_toolchain",
    srcs = ["trivy_toolchain.bzl"],
    visibility = ["//lib:__subpackages__"],
    deps = [
    ],
)

bzl_library(
    name = "toolchain_factory",
    srcs = ["toolchain_factory.bzl"],
    visibility = ["//lib:__subpackages__"],
    deps = [
    ],
)

bzl_library(
    name = "buildifier_toolchain",
    srcs = ["buildifier_toolchain.bzl"],
    visibility = ["//lib:__subpackages__"],
    deps = [
    ],
)

bzl_library(
    name = "scanner_factory",
    srcs = ["scanner_factory.bzl"],
    visibility = ["//lib:__subpackages__"],
    deps = [
    ],
)
