load("@aspect_bazel_lib//lib/private:repo_utils.bzl", "repo_utils")

# Helm distributes tarballs containing <os>-<arch>/helm inside.
# URL pattern: https://get.helm.sh/helm-v<version>-<os>-<arch>.tar.gz

_binaries = {
    "3.16.4": {
        "darwin_amd64": ("https://get.helm.sh/helm-v3.16.4-darwin-amd64.tar.gz", "8dc25671120a4af197afe7ad9041fb8e1dd71bc01e5ef73dba1139cbc9e9f44b"),
        "darwin_arm64": ("https://get.helm.sh/helm-v3.16.4-darwin-arm64.tar.gz", "e2442d8f05d53d84c39b869bc5fe5affad247ee2f4c706a040919c146edb1f94"),
        "linux_amd64": ("https://get.helm.sh/helm-v3.16.4-linux-amd64.tar.gz", "fc307327959aa38ed8f9f7e66d45492bb022a66c3e5da6063958254b9767d179"),
        "linux_arm64": ("https://get.helm.sh/helm-v3.16.4-linux-arm64.tar.gz", "d3f8f15b3d9ec8c8678fbf3280c3e5902efabe5912e2f9fcf29107efbc8ead69"),
    },
}

DEFAULT_HELM_VERSION = "3.16.4"
DEFAULT_HELM_REPOSITORY = "helm"

HELM_PLATFORMS = {
    "darwin_amd64": struct(
        release_platform = "darwin-amd64",
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
    ),
    "darwin_arm64": struct(
        release_platform = "darwin-arm64",
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
    ),
    "linux_amd64": struct(
        release_platform = "linux-amd64",
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    ),
    "linux_arm64": struct(
        release_platform = "linux-arm64",
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
    ),
}

HelmInfo = provider(
    doc = "Provide info for executing helm",
    fields = {
        "bin": "Executable helm binary",
    },
)

def _helm_toolchain_impl(ctx):
    binary = ctx.file.bin

    # Make the $(HELM_BIN) variable available in places like genrules.
    # See https://docs.bazel.build/versions/main/be/make-variables.html#custom_variables
    template_variables = platform_common.TemplateVariableInfo({
        "HELM_BIN": binary.path,
    })
    default_info = DefaultInfo(
        files = depset([binary]),
        runfiles = ctx.runfiles(files = [binary]),
    )
    helm_info = HelmInfo(
        bin = binary,
    )

    # Export all the providers inside our ToolchainInfo
    # so the resolved_toolchain rule can grab and re-export them.
    toolchain_info = platform_common.ToolchainInfo(
        helminfo = helm_info,
        template_variables = template_variables,
        default = default_info,
    )

    return [default_info, toolchain_info, template_variables]

helm_toolchain = rule(
    implementation = _helm_toolchain_impl,
    attrs = {
        "bin": attr.label(
            mandatory = True,
            allow_single_file = True,
            executable = True,
            cfg = "exec",
        ),
    },
)

def _helm_toolchains_repo_impl(rctx):
    # Expose a concrete toolchain which is the result of Bazel resolving the toolchain
    # for the execution or target platform.
    # Workaround for https://github.com/bazelbuild/bazel/issues/14009
    starlark_content = """# @generated by @rules_k8s_cd//helm_toolchain.bzl

# Forward all the providers
def _resolved_toolchain_impl(ctx):
    toolchain_info = ctx.toolchains["@rules_k8s_cd//lib:helm_toolchain_type"]
    return [
        toolchain_info,
        toolchain_info.default,
        toolchain_info.helminfo,
        toolchain_info.template_variables,
    ]

# Copied from java_toolchain_alias
# https://cs.opensource.google/bazel/bazel/+/master:tools/jdk/java_toolchain_alias.bzl
resolved_toolchain = rule(
    implementation = _resolved_toolchain_impl,
    toolchains = ["@rules_k8s_cd//lib:helm_toolchain_type"],
)
"""
    rctx.file("defs.bzl", starlark_content)

    build_content = """# @generated by @rules_k8s_cd//lib/private:helm_toolchain.bzl
#
# These can be registered in the workspace file or passed to --extra_toolchains flag.
# By default all these toolchains are registered by the helm_register_toolchains macro
# so you don't normally need to interact with these targets.

load(":defs.bzl", "resolved_toolchain")

resolved_toolchain(name = "resolved_toolchain", visibility = ["//visibility:public"])

"""

    for [platform, meta] in HELM_PLATFORMS.items():
        build_content += """
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    toolchain = "@{user_repository_name}_{platform}//:helm_toolchain",
    toolchain_type = "@rules_k8s_cd//lib:helm_toolchain_type",
)
""".format(
            platform = platform,
            user_repository_name = rctx.attr.user_repository_name,
            compatible_with = meta.compatible_with,
        )

    # Base BUILD file for this repository
    rctx.file("BUILD.bazel", build_content)

helm_toolchains_repo = repository_rule(
    _helm_toolchains_repo_impl,
    doc = """Creates a repository with toolchain definitions for all known platforms
     which can be registered or selected.""",
    attrs = {
        "user_repository_name": attr.string(doc = "Base name for toolchains repository"),
    },
)

def _helm_platform_repo_impl(rctx):
    meta = HELM_PLATFORMS[rctx.attr.platform]
    url, sha256 = _binaries[rctx.attr.version][rctx.attr.platform]

    # Helm tarballs contain <os>-<arch>/helm inside the archive.
    # Using stripPrefix strips that directory so only `helm` (and LICENSE/README) remain.
    rctx.download_and_extract(
        url = url,
        sha256 = sha256,
        stripPrefix = meta.release_platform,
    )

    rctx.file("BUILD.bazel", """# @generated by @rules_k8s_cd//lib/private:helm_toolchain.bzl
load("@rules_k8s_cd//lib/private:helm_toolchain.bzl", "helm_toolchain")
exports_files(["helm"])
helm_toolchain(name = "helm_toolchain", bin = "helm", visibility = ["//visibility:public"])
""")

helm_platform_repo = repository_rule(
    implementation = _helm_platform_repo_impl,
    doc = "Fetch external tools needed for helm toolchain",
    attrs = {
        "platform": attr.string(mandatory = True, values = HELM_PLATFORMS.keys()),
        "version": attr.string(mandatory = False, default = DEFAULT_HELM_VERSION, values = _binaries.keys()),
    },
)

def _helm_host_alias_repo(rctx):
    ext = ".exe" if repo_utils.is_windows(rctx) else ""

    # Base BUILD file for this repository
    rctx.file("BUILD.bazel", """# @generated by @rules_k8s_cd//lib/private:helm_toolchain.bzl
package(default_visibility = ["//visibility:public"])

exports_files(["helm{ext}"])
""".format(
        ext = ext,
    ))

    rctx.symlink("../{name}_{platform}/helm{ext}".format(
        name = rctx.attr.name,
        platform = repo_utils.platform(rctx),
        ext = ext,
    ), "helm{ext}".format(ext = ext))

helm_host_alias_repo = repository_rule(
    _helm_host_alias_repo,
    doc = """Creates a repository with a shorter name meant for the host platform, which contains
    a BUILD.bazel file that exports symlinks to the host platform's binaries
    """,
)
