"""Factory for creating toolchain rules with identical structure.

This module eliminates duplication across grype, dive, trivy, and kyverno
toolchain definitions, which all follow the same pattern.
"""

load("@aspect_bazel_lib//lib/private:repo_utils.bzl", "repo_utils")
load("//lib:repo_utils.bzl", "download_toolchain_binary")

def create_toolchain(name, binaries, platforms):
    """Creates all toolchain-related rules and providers for a tool.

    Args:
        name: Tool name (e.g., "grype", "dive").
        binaries: Dict mapping platform keys to (url, sha256) tuples.
        platforms: Dict mapping platform keys to structs with compatible_with.

    Returns:
        A struct with: info_provider, toolchain_rule, toolchains_repo,
        platform_repo, host_alias_repo.
    """

    # Create the provider
    info_provider = provider(
        doc = "Provide info for executing " + name,
        fields = {
            "bin": "Executable " + name + " binary",
        },
    )

    # Provider field name used in ToolchainInfo (e.g., "grypeinfo")
    info_field = name + "info"

    # Template variable name (e.g., "GRYPE_BIN")
    template_var = name.upper() + "_BIN"

    # Toolchain type label
    toolchain_type = "@rules_k8s_cd//lib:" + name + "_toolchain_type"

    def _toolchain_impl(ctx):
        binary = ctx.file.bin

        template_variables = platform_common.TemplateVariableInfo({
            template_var: binary.path,
        })
        default_info = DefaultInfo(
            files = depset([binary]),
            runfiles = ctx.runfiles(files = [binary]),
        )
        tool_info = info_provider(
            bin = binary,
        )

        toolchain_info = platform_common.ToolchainInfo(
            **{
                info_field: tool_info,
                "template_variables": template_variables,
                "default": default_info,
            }
        )

        return [default_info, toolchain_info, template_variables]

    toolchain_rule = rule(
        implementation = _toolchain_impl,
        attrs = {
            "bin": attr.label(
                mandatory = True,
                allow_single_file = True,
                executable = True,
                cfg = "exec",
            ),
        },
    )

    def _toolchains_repo_impl(rctx):
        starlark_content = """# @generated by @rules_k8s_cd//{name}_toolchain.bzl

# Forward all the providers
def _resolved_toolchain_impl(ctx):
    toolchain_info = ctx.toolchains["{toolchain_type}"]
    return [
        toolchain_info,
        toolchain_info.default,
        toolchain_info.{info_field},
        toolchain_info.template_variables,
    ]

# Copied from java_toolchain_alias
# https://cs.opensource.google/bazel/bazel/+/master:tools/jdk/java_toolchain_alias.bzl
resolved_toolchain = rule(
    implementation = _resolved_toolchain_impl,
    toolchains = ["{toolchain_type}"],
)
""".format(
            name = name,
            toolchain_type = toolchain_type,
            info_field = info_field,
        )
        rctx.file("defs.bzl", starlark_content)

        build_content = """# @generated by @rules_k8s_cd//lib/private:{name}_toolchain.bzl
#
# These can be registered in the workspace file or passed to --extra_toolchains flag.
# By default all these toolchains are registered by the {name}_register_toolchains macro
# so you don't normally need to interact with these targets.

load(":defs.bzl", "resolved_toolchain")

resolved_toolchain(name = "resolved_toolchain", visibility = ["//visibility:public"])

""".format(name = name)

        for [platform, meta] in platforms.items():
            build_content += """
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    toolchain = "@{user_repository_name}_{platform}//:{name}_toolchain",
    toolchain_type = "{toolchain_type}",
)
""".format(
                platform = platform,
                name = name,
                user_repository_name = rctx.attr.user_repository_name,
                compatible_with = meta.compatible_with,
                toolchain_type = toolchain_type,
            )

        rctx.file("BUILD.bazel", build_content)

    toolchains_repo = repository_rule(
        _toolchains_repo_impl,
        doc = """Creates a repository with toolchain definitions for all known platforms
     which can be registered or selected.""",
        attrs = {
            "user_repository_name": attr.string(doc = "Base name for toolchains repository"),
        },
    )

    def _platform_repo_impl(rctx):
        download_toolchain_binary(
            rctx = rctx,
            toolchain_name = name,
            platform = rctx.attr.platform,
            binary = binaries[rctx.attr.platform],
        )

    platform_repo = repository_rule(
        implementation = _platform_repo_impl,
        doc = "Fetch external tools needed for " + name + " toolchain",
        attrs = {
            "platform": attr.string(mandatory = True, values = platforms.keys()),
        },
    )

    def _host_alias_repo_impl(rctx):
        ext = ".exe" if repo_utils.is_windows(rctx) else ""

        rctx.file("BUILD.bazel", """# @generated by @rules_k8s_cd//lib/private:{name}_toolchain.bzl
package(default_visibility = ["//visibility:public"])
exports_files(["{name}{ext}"])
""".format(
            name = name,
            ext = ext,
        ))

        rctx.symlink("../{repo_name}_{platform}/{name}{ext}".format(
            repo_name = rctx.attr.name,
            platform = repo_utils.platform(rctx),
            name = name,
            ext = ext,
        ), "{name}{ext}".format(name = name, ext = ext))

    host_alias_repo = repository_rule(
        _host_alias_repo_impl,
        doc = """Creates a repository with a shorter name meant for the host platform, which contains
    a BUILD.bazel file that exports symlinks to the host platform's binaries
    """,
    )

    return struct(
        info_provider = info_provider,
        toolchain_rule = toolchain_rule,
        toolchains_repo = toolchains_repo,
        platform_repo = platform_repo,
        host_alias_repo = host_alias_repo,
    )
